### ISSUE TITLE
Implement skeletal active-passive sync

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#1209]
In the same way that #1208 deals with replicating cache lifecycle events to the passive entity, this task adds support for communicating existing cache lifecycle states during passive sync, before allowing a newly arriving passive entity to enter standby state.

**Comment by chrisdennis** [comment]
Blocked by #1207 (and closely linked to #1208)

**Comment by ljacomet** [comment]
Additional outcome: some documentation on the design of this

**Comment by AbfrmBlr** [comment]
There is a limitation of syncing data during active-passive sync. It's because of the difference between no. of segments of `ServerStore` & `DEFAULT_CONCURRENCY`.
Right now all the operations, irrespective of being mutative or not are spread across the `DEFAULT_CONCURRENCY` i.e. 1024 keys across all caches.
The spread is defined by the hash of `cacheId` & key (mod 1024) calculated at client side. This results in calling `syncToPassive` on all concurrency keys. The problem is there is no way for entity to figure out, what all data is mapped to a particular concurrency key for which platform will try to sync. 

The idea is to stick with the same spread for reads (including replace), but change the mutations spread to (no. of caches * segments = 16)%1024 (an additional factor can also be multiplied in future to reduce the sync time for a segment). In this way for the chosen sync keys, the Active entity exactly knows which segment to sync.

Note:- Both No of segments in `ServerStore` and `DEFAULT_CONCURRENCY` can be changed.

All this came up in discussion with @ljacomet , @albinsuresh , @itsroshan , @rkavanap & sairam
