### ISSUE TITLE
Implement Passive Key/Value Replication

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#1211]
This is the meat of the passive-sync solution that has been discussed in detail in various mail threads and meetings.

**Comment by chrisdennis** [comment]
Blocked by #1208 (and likely by #1209 too)

**Comment by ljacomet** [comment]
Additional outcome: some documentation on the design

**Comment by AbfrmBlr** [comment]
Handling Inflight Client Invalidations during failover :-

Right now we send InvalidationIds(server generated) to all the clients waiting to be invalidated. As and when we get the ack back the bookkeeping is updated and once all the clients have acked backed, the originating client is told that invalidation is complete. Now the problem is what happens if the failover happens during the invalidations are still in progress.
The way it can be solved is to add more states at client sides, The first thing is to maintain a higher watermark of invalidation ids at all the clients and the other thing is to  maintain pair of hash - invalidationId at all the originating clients until the invalidation is complete. 
Both of the these information will help newly promoted Active to regain the (nearly)same state as of earlier active. This helps entity to know about all the waiting originating client and inflight invalidations. 

Now when the first invoke comes to entity after all the handleReconnects are completed, entity sends all the invalidations again(which may end up having duplicate ones at clients, but that's fine higher watermark is at help there).

Handling Passive eviction followed by a failover :- 

This can be handled based on the fact that every eviction at passive can be tracked until it is followed by a replaceAtHead, thus during failover newly promoted Active can invalidate all the clients having that hash which is still not replaced.

**Comment by AbfrmBlr** [comment]
As of now the scheme for replication of append/getAndAppend has to use `IEntityMessenger` api from active entity to send the updated chain(after invoke) to the passive entity so that passive can attain the same state as the Active for that hash. This can lead to really large chains getting replicated to passive. Since our most used operation `get` mandates an asynchronous call to replaceAtHead, similarly other operations can also asynchronously call replaceAtHead. So as an optimization for later(iff found worthy enough), we can decide to invoke `IEntityMessenger` api for the replaceAtHead message from the client as the sub-operation for the corresponding append/getAndAppend operations. This will help us gain throughput for write operations as they can complete without waiting for Active-Passive replication of the original append/getAndAppend operation, as that can be taken care by asynchronous replaceAtHead calls done by clients. I think this should work without any major concerns.It will also depend on what other optimization is enabled at the server side to resolve the chain.
