### ISSUE TITLE
problem get jconsole monitor working

### ISSUE THREAD

**Issue by Martian101** [ehcache/ehcache3#1335]
I use ehcache 3. when i try to register to a Mbean server with such code:
```
			MBeanServer mBeanServer = ManagementFactory.getPlatformMBeanServer();
			ManagementService.registerMBeans((net.sf.ehcache.CacheManager) cacheManager, mBeanServer, true, true, true, true);
```
I got a ClassCastException:
`java.lang.ClassCastException: org.ehcache.core.EhcacheManager cannot be cast to net.sf.ehcache.CacheManager `

Things turn out that a CacheManager  of ehcache3 to a CacheManager of ehcache2. How can i succefully register to a MbeanServer use ehcache3? Or is it a feature not implemented?

**Comment by ljacomet** [comment]
Hi,

Thanks for you interest in Ehcache 3.

We recommend to start conversations on the [google groups](https://groups.google.com/forum/#!forum/ehcache-users) instead of filing issues directly.

There is no way you can cast an Ehcache 3 `CacheManager` to the Ehcache 2.x type for one.
So indeed the `ManagementService` is not usable in Ehcache 3.

There is currently no native support for that. An alternative is to use JCache APIs instead which will allow MBeans to be registered.

As to how it will fit your use case, more information is needed as to what you want out of MBeans registration.

**Comment by ljacomet** [comment]
Closing as invalid given the lack of follow up
