### ISSUE TITLE
Ehcache3.1.1 xml parser error

### ISSUE THREAD

**Issue by chxiaowu** [ehcache/ehcache3#1395]
<eh:config

    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:eh='http://www.ehcache.org/v3'
    xmlns:jsr107='http://www.ehcache.org/v3/jsr107'
    xsi:schemaLocation="
        http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.1.xsd
        http://www.ehcache.org/v3/jsr107 http://www.ehcache.org/schema/ehcache-107-ext-3.1.xsd">

	<eh:cache alias="respCache">
		<eh:heap unit="entries">2000</eh:heap>
		<eh:expiry>
			<eh:ttl unit="seconds">15</eh:ttl>
		</ch:expiry>
	</eh:cache>

</eh:config>

java:
	                org.springframework.core.io.ClassPathResource resource = new ClassPathResource("ehcache.xml");
			Configuration xmlConfig = new XmlConfiguration(resource.getURL());
			cacheManager = CacheManagerBuilder.newCacheManager(xmlConfig);

error：
'eh:expiry'  start elements invalid???

expiry not for heap!

So, how to set ttl for elements cached in heap???

**Comment by albinsuresh** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We usually recommend starting a conversation on the [users google group](https://groups.google.com/forum/#!forum/ehcache-users) before opening an issue.

Now coming to your problem, there are two issues with your xml config:

1. The expiry element's closing tag has a typo: `</ch:expiry>` instead of `</eh:expiry>`
2. The position of the expiry element is not following the xsd rules. The Ehcache xsd mandates the `<expiry>` element to appear before the resource element (heap in your case). Changing that order should fix your issue.

**Comment by ljacomet** [comment]
Closing following comments from @albinsuresh
