### ISSUE TITLE
Support system properties replacement in Ehcache xml

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#1429]
As requested [on the mailing list](https://groups.google.com/forum/#!category-topic/ehcache-users/ehcache-core/sUC_WBDFT8g) this is a feature that makes sense.

@alexsnaps already made an initial PR to support this -see #1426 
I believe it is a good start but it misses enabling substitution for attributes / element text that are defined as numbers.
For example in `<heap>10</heap>`.

And also there is a remark about NCname problems.

So this issue exists to track exactly what will be possible / supported and what will not regarding property substitution.

**Comment by alexsnaps** [comment]
If I understand this right, NCname and the "missing" support for numbers is the same issue: i.e. you can't specify a system property where the current XSD prohibits it based in the expected type (`xs:ID`, `xs:positiveInteger`, ...).

But that's sort of by design, as I had two options as I see it:
 - Implement the substitution _before_ the validation (bypassing these issues); or
 - Implement it, _after_ the validation (which is what I did).

The rational is that I think it's "nicer" to _not_ break tooling support, whether that is editor support for the developer, or even validation support (say using `xmllint`) for ops guys to make sure they never deploy a broken config. I think system-props shouldn't be anything special from that regard.

So I think all those places where substitution is to be supported, we could either go for a regex or use a `psd:union` for either one _or_ the other (i.e. say it's either `50` (`xs:positiveInteger`) _or_ a system prop (own defined type that would be string + regex to match `${.*}`.

Depending on all the places we're talking about it seems "cleaner" and "safer", as while partial substitutions make sense for some cases (all `xs:string`?) e.g. `${user.dir}/ehcache/data/myCM`, I feel '`1${someProp}` is rather contorted!...

**Comment by alexsnaps** [comment]
Maybe rolling it out phased is the answer: i.e. only support substitution when the _current_ (and not a relaxed) XSD supports it and see if that addresses 90% of the problems?

**Comment by ljacomet** [comment]
Ok, got it. I missed the bit about IDs being NCname.

I agree with your comments though - where we can for now, let's support the scheme you proposed: in strings, you can have multiple substitutions.

And indeed let's investigate what happens when we try to enable something that would be an _OR_ between a number or a simple substitution.

**Comment by alexsnaps** [comment]
Not sure what you mean now... phased rollout? Or let's investigate now already first? 
If the former, I guess you now want me to clean up the PR, y? ;)

**Comment by ljacomet** [comment]
What's in your PR is self contained, so that could go in already - so yes, phased rollout.

**Comment by alexsnaps** [comment]
Well, there is an adapted version... Hope this helps!

**Comment by chrisdennis** [comment]
Not sure I like the idea of blanket XML wide parameter substitution, seems like this might be stepping out on to a slippery slope for the hell of it.  Could we maybe switch to instead targetting parameter substitution to only certain strings, and doing it at a later stage in configuration processing.  (Possibly even late enough that it would be common between XML and programmatic configuration handling).

**Comment by alexsnaps** [comment]
I personally really dislike the mashing of substitutions at the programmatic configuration. If you want props in your programmatic configuration, just do it. But I wouldn't add a "language" for that. 

As with regards to your point to "blanket XML wide", I initially didn't feel comfortable with it really neither. Then, seeing the limitation imposed by the validation it felt less intrusive, but also consistent (i.e. happens in other extensions/namespaces just identically). 

So all in all it felt right. Now, another option is instead of supporting all `xs:string` (I don't think anything else would work) by incident, we could make it explicit. Introduce a custom type where substitution happens (e.g. `ehcache:substituableString` or something) and only those would then also support it. If that's the case, JAXB maybe a better abstraction to introduce that behavior though.

**Comment by henri-tremblay** [comment]
I haven't looked at the full proposal but my take on that is that
everything should be replaceable by any variable. That's what I use will
expect. Anything short from that will feel inexplicable.

I also agree with @alexsnaps. If someone want programmatic replacement,
they should code it.

**Comment by alexsnaps** [comment]
@henri-tremblay just to be sure: if anything is substitutable (and I guess you mean every value, though!), would a "fully to substitute" xml file also still validate _prior_ the substitution? 

If so, then I think the way forward is to introduce every `substitutable<Type>` and use these instead of "straight XSD types". That being said, I'm not sure I agree _everything_ should be. There is stuff that's just contextual, e.g. use 20% of a given resource pool (not sure that's even yet/eventually). 

I'm thinking all "standalone" values make sense for substitution. Anything further seems to call for different configs altogether, the one used at runtime to be then identified by a system prop maybe. But otherwise that seems to push the indirections a bit too far imho.

**Comment by henri-tremblay** [comment]
Ok. Let's be precise on "everything".

I don't mean the full XML text can contain tokens all over the place. So I
mean actual TEXT and attributes.

Then, we can argue that it is useless to be able to rename a cache let's
say. But I don't think it matters if we allow it.

**Comment by alexsnaps** [comment]
On the former that's what I understood. But do we agree that it should validate? If so, do you think the `substitutable<Type>` is the one to take? It's a non-neglactable change to... everything.

As for allowing vs. disallowing, in this case I think it's more enabling vs. plain rolling out an abstraction throughout the XML parsing. The advantage I see in being slightly more "prohibitive" is to have the "limitations" naturally lead to the "better" solution. Actually going through the values that are currently (on that branch) substitutable, maybe only the persistence dir is the one thing sensible. And my approach was just flawed to begin with and we should deal with that one on its own.

**Comment by ljacomet** [comment]
Regarding IDs: I am fine with not supporting replacements there. It currently covers cache and template names. The later just makes no sense since template names are to be used mostly inside the config file itself. As for the former, I have a hard time seeing any serious benefit there.

**Comment by ljacomet** [comment]
As stated in #1426, we are starting with:
* Support replacement in text attributes or nodes - that is where `$`, `{` and `}` are valid characters
* Blanket property replacement - using `${prop.name}` as the format
* An exception will be thrown if the substitution cannot resolve a value
* There is currently no way of escaping the `${some.text}` pattern

**Comment by ljacomet** [comment]
Closing this for now as it will be part of 3.1.3 - let's open new issues if we want to expand this in the 3.2.x line.

**Comment by buksvdl** [comment]
You don't see a need for env properties for e.g
` <expiry>
      <tti unit="seconds">48000</tti>
    </expiry>`

**Comment by gabydinu** [comment]
it might be useful to be able to configure 
<terracotta:connection url="${ehcache.cluster.server}" /> 
also in a property file outside war app
