### ISSUE TITLE
Support of iterating a cacheMap removed?

### ISSUE THREAD

**Issue by savdeep** [ehcache/ehcache3#1450]
Hi,

I was just iterating a cacheMap and got unsupported operation exception. This same case worked before in 2.7 version? Is this support removed from latest version?

**Comment by ljacomet** [comment]
Hi,

Thanks for your interest in Ehcache 3.

We request to start conversations on the [mailing list](https://groups.google.com/forum/#!forum/ehcache-users) before opening an issue.

Now, before being able to answer your problem, can you specify which version of Ehcache you are using and exactly which method on which type. Because `cacheMap` does not ring a bell.

**Comment by savdeep** [comment]
Thanks a lot for the quick reply.

I am using version 3.1.
