### ISSUE TITLE
Add `Ehcache` unit tests (non-bulk)

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#147]
It seems like it certainly misses unit tests for the Concurrent CRUD operations. But there might be more. We want this class to have a very good code coverage before releasing!

**Comment by chrisdennis** [comment]
There are still a bunch of "Confirm Correctness TODOs left in the code that originating in this commit.  Since @cljohnso explicitly called them out in this issue I'm reopening it handle resolving those TODOs:

https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicPutIfAbsentTest.java#L212
https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicPutIfAbsentTest.java#L241
https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicPutIfAbsentTest.java#L346

https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicRemoveValueTest.java#L481
https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicRemoveValueTest.java#L603

https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicReplaceValueTest.java#L795

**Comment by chrisdennis** [comment]
Replaced with #930
