### ISSUE TITLE
Implement active-passive data sync

### ISSUE THREAD

**Issue by albinsuresh** [ehcache/ehcache3#1479]
In #1210 we decided that a passive joining a cluster must be fully synced with all the key-value pairs in the active. So this task is to implement the same in the least disruptive manner. The active should not be fully blocked while the sync is being performed. Instead, the sync should be performed per concurrency key so that there's only concurrency key level blocking on the active.

**Comment by albinsuresh** [comment]
Summarizing the points raised in discussion threads that happened elsewhere:

There is a limitation of syncing data during active-passive sync. It's because of the difference between no. of segments of `ServerStore` & `DEFAULT_CONCURRENCY`.
Right now all the operations, irrespective of being mutative or not are spread across the `DEFAULT_CONCURRENCY` i.e. 1024 keys across all caches.
The spread is defined by the hash of `cacheId` & key (mod 1024) calculated at client side. This results in calling `syncToPassive` on all concurrency keys. The problem is there is no way for entity to figure out, what all data is mapped to a particular concurrency key for which platform will try to sync. 

The idea is to stick with the same spread for reads (including replace), but change the mutations spread to (no. of caches * segments = 16)%1024 (an additional factor can also be multiplied in future to reduce the sync time for a segment). In this way for the chosen sync keys, the Active entity exactly knows which segment to sync.

Note:- Both No of segments in `ServerStore` and `DEFAULT_CONCURRENCY` can be changed.

All this came up in discussion with @ljacomet , @albinsuresh , @itsroshan , @rkavanap & sairam

**Comment by ljacomet** [comment]
Adding to the design:

* Read operations should use the `UNIVERSAL_KEY` as they have no ordering requirement
* For write operations, we need to move to a scheme matching the segment of the underlying store.

For this second point, the following has been discussed and is the latest design:
* When a new clustered tier is created, a `reconfigure` message will be sent to the entity with the added information for this new tier - offset and segments count.
** This means that the create operation must return this information, so that the client can then invoke reconfigure
** This also means that the configuration object which is currently limited to a UUID needs to be expanded to carry that information.
* Once reconfigure is called, this causes the entity and `ConcurrencyStrategy` to be recreated based on that new information
* With the information, the `ConcurrencyStrategy` will have to use the same hash and bucketing algorithm as the matching store to determine the proper concurrency key.

For example, with store `foo` and `bar`, assuming 16 segments like right now, we would have the following spaces:
* `foo` from 2 to 17 (so offset is 2, key space is 16)
* `bar` from 18 to 33 (so offset is 18, key space is 16)
