### ISSUE TITLE
Load EhCache diskstore content into memory

### ISSUE THREAD

**Issue by aihaiyue123** [ehcache/ehcache3#1702]
Load EhCache diskstore content into memory

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

Also the issue here does not make clear what the problem is or what would need to be changed / improved.
Unless there is a comment in the next 24h, I will close this issue.

**Comment by ljacomet** [comment]
Closing as indicated
