### ISSUE TITLE
Add Serializer to XML config

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#182]
The `ehcache-core.xsd` in the xml module doesn't let you configure a `org.ehcache.spi.serialization.Serializer` for a given `Cache` configured in XML. We probably want to support this a both `<cache/>` and `<cache-template/>` levels

**Comment by AbfrmBlr** [comment]
SerializationProvider should not be the part of the CacheConfiguration but as of now it needs to be part of the Store.Configuration.
Reason being OnHeapStore needs key and value serializers but DiskStore uses different serializers(for Element and Object).
Would it make sense to retain SerializationProvider as part of Store.Configuration so that the Stores can get the serializers as required?

**Comment by AbfrmBlr** [comment]
To enable Serializers to be configured from xml requires extension of ehcache-core.xsd with a different namespace.(just like jsr107 service)
DefaultSerializationProvider(JavaSerializationProvider in this case) will fall in a different namespace in xsd with a parser implemented. This requires a new project, as having it in impl creates a cyclic dependency among projects.
If the ehcache user wants to use a different SerializationProvider, he will have to create another namepsace and write the parser again(or may be he can reuse the one implemented for the DefaultSerializationProvider).This will hold true for all the Services with ServiceConfiguration. Is it the right understanding ?
