### ISSUE TITLE
Search API is missing some useful criterias, e.g. isNull(), isNotNull, contains(Collection<T> items)

### ISSUE THREAD

**Issue by madness-inc** [ehcache/ehcache3#190]
For some advanced search queries, the above mentioned methods would be very useful.
Example:

``` java
Attribute<Integer> foo = cache.getSearchAttribute("foo");
Attribute<Integer> bar = cache.getSearchAttribute("bar");
Attribute<Integer> categories = cache.getSearchAttribute("categories");
Query query = cache.createQuery().includeValues();
query.addCriteria(foo.isNull());
query.addCriteria(bar.isNotNull());
query.addCriteria(categories.contains(Arrays.asList(1,2,3)));
```

**Comment by marcodelpercio** [comment]
Why there is no search api in 3.x ?? I think it was one of the best features

**Comment by alexsnaps** [comment]
Searching over what's in a Cache, i.e. what currently happens to be the
hotset based on the cache access pattern, has no semantic really.
Say, what's the average salary of all the employees currently in the Cache?
This means nothing. It only means something is the cache knows about the
complete population of Employees. Which is a guarantee a Cache will never
give you.

**Comment by marcodelpercio** [comment]
Well actually the search api was useful for querying data where ehcache could provide an in-memory dataset. Something like H2 yet with the advantages of ehcache.
There are other products providing in-memory dataset querying but I thought that ehcache was a good candidate for that, if this feature is removed in v3 then we better go for a different product

**Comment by alexsnaps** [comment]
Totally in agreement here... that's indeed another product than ehcache.
Ehcache "only" provides a Caching API.
As for an in-memory datagrid that provides you with a search API (and
possibly more), well... there are other products out there today, and
probably more so in the future ;)

**Comment by marcodelpercio** [comment]
I see,

It's a shame I thought it was quite promising, there're several articles comparing ehcache with other in-memory datagraid products and since we didn't need synchronization with different nodes
ehcache was quite good in it.

**Comment by alexsnaps** [comment]
Well, actually it sorts of got really bad with the new topologies supported
with 3.0.
Let me explain: OSS Ehcache only supported brute forcing in order to
search, which works fine on "small" heap caches. With the offheap store now
being open sourced, one could easily have multiple 10GB of data in a cache
on low end commodity hardware. Coupled with the fact that deserialization
would be required to evaluate against each attribute, well, latency starts
looking very bad.
Long story short, if you know all the data in a cache is all you need to
query, you probably could implement the logic yourself outside of the cache
pretty quickly. But performance would degrade rapidly as the dataset grows.
If you don't worry about that cool, but as library developers we can't
possibly take that approach. It'd be a disservice to our users.
Now we are working on something else to cover these larger dataset use
cases. It won't happen through the Ehcache API though.
Hope this makes some sense.
