### ISSUE TITLE
ehcache crashes whole JVM if a diskstore tier is utilized on more than 4000 caches

### ISSUE THREAD

**Issue by bjanczak** [ehcache/ehcache3#1932]
Issue details reported on ehcache-users forum: https://groups.google.com/forum/#!searchin/ehcache-users/ehcache$20crashes$20whole$20JVM%7Csort:relevance/ehcache-users/nPGHVqL_0kI/sDuFgHa8BQAJ

In short. Disk storages are separated in 16 segments. We would like to have it configurable.

**Comment by henri-tremblay** [comment]
As mentioned in the Google group, I was able to create 4000 caches on Ubuntu without any problem by changing only the max open files. So I suspect the problem comes from an OS setup. That said, if the JVM is crashing (I thought it was an OOME), it shouldn't. So that would mean a JVM bug as well. Which might be fixed in newer versions.

That said, I think the 16 segments should be configurable. For small caches, 16 can be a little overkill so one might want to trade off concurrency for a lower resource usage. My PR will do that.

**Comment by ljacomet** [comment]
Flagging for `3.4.0` since this requires API and XSD additions.
