### ISSUE TITLE
Issue opening .jar file

### ISSUE THREAD

**Issue by jack17529** [ehcache/ehcache3#1961]
![jar file error](https://cloud.githubusercontent.com/assets/15366183/25070389/48672970-22ba-11e7-88f2-fdd2d342ca05.png)

**Comment by henri-tremblay** [comment]
Ehcache is an open source framework developed by a lot of nice people. Partly because it's their job and partly on their free time. So in general, people are nice with us and ask kindly for help. This applies to every other open source software as well.

Here you seem to think GitHub is a global helpdesk for any unrelated issue you might here. So you file a vague title and two screenshots.

That's not the way it works:
- An issue should have an full explanation with a maximum of details
- The title should tell the actual issue, not that it is an issue
- In our case, you should ask such issue to the mailing list first
- It should linked with the actual usage of Ehcache. Not opening a jar by double-clicking on it

Your current problem is that you have tried to execute ehcache by double-clicking on it. It is linked with launching java but comes from the Internet. So it has to do with the Ubuntu security manager and file associations. Not with ehcache. Which is why I will close the issue.

Please, if you want to be helped and contribute to open source software, follow the guideline above.

**Comment by jack17529** [comment]
Very sorry writing issue so badly , please forgive me. I need to mind this as I do weird things under pressure.
Thanks for the answer.
