### ISSUE TITLE
How to enable Ehcache 3.x JSR-107 MBean operations?

### ISSUE THREAD

**Issue by m-titov** [ehcache/ehcache3#1993]
Why the following ehcache.xml doesn't allow to clear caches via JMX (the Operations tab is disabled in JVisualVM for MBean for cache management and enabled for cache statistic)?

```
<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.ehcache.org/v3'
    xmlns:jsr107='http://www.ehcache.org/v3/jsr107'
    xsi:schemaLocation="
        http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.0.xsd
        http://www.ehcache.org/v3/jsr107 http://www.ehcache.org/schema/ehcache-107-ext-3.0.xsd">


  <service>
    <jsr107:defaults enable-management="true" enable-statistics="true"/> 
  </service>

  <cache alias="stringCache"> 
    <key-type>java.lang.String</key-type>
    <value-type>java.lang.String</value-type>
    <heap unit="entries">2000</heap>
  </cache>

</config>
```

**Comment by henri-tremblay** [comment]
Please, ask questions through stackoverflow or our [mailing list](ehcache-users@googlegroups.com) next time.

What you are doing should work. The problem is probably coming from the way you are creating the cache manager. Here is the code I used to test and that works:

```
public class App 
{
    public static void main( String[] args ) throws Exception {
        CachingProvider provider = Caching.getCachingProvider();
        try(CacheManager cacheManager = provider.getCacheManager(App.class.getResource("/ehcache.xml").toURI(), App.class.getClassLoader())) {
            Cache<String, String> cache = cacheManager.getCache("stringCache", String.class, String.class);
            while (true) {
                cache.put(UUID.randomUUID().toString(), "aaaa");
                TimeUnit.SECONDS.sleep(1);
            }
        }
    }
}
```

However, I highly suspect that you are looking at the cache configuration instead of the cache statistics in JMX. Also, please note that the clear is used to clear the statistics, not the cache.

**Comment by m-titov** [comment]
Hi Henry.

**Comment by anthonydahanne** [comment]
cross posted : https://stackoverflow.com/questions/44164986/how-to-enable-ehcache-3-x-jsr-107-mbean-operations

**Comment by henri-tremblay** [comment]
No. You will not be able to clear the cache from VisualVM unless you do your own MBean. The JSR-107 specification allows for cache statistics clearing, not cache clearing.

And yes, if you use `@EnableCaching` and `spring.cache.jcache.config=ehcache.xml` everything will get magically configured. However, in that case, your `ehcache.xml` is incorrect. You need to remove the key and value types on your cache. Spring doesn't like typed caches (because it put types that a unknown to you in the cache).

**Comment by m-titov** [comment]
Thanks a lot
