### ISSUE TITLE
Enable osgi-test module in Java 9

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#2010]
The merging of the Java 9 testing support required us to disable the OSGi tests in Java 9.  I believe the very latest versions of Apache Felix (5.6.2+) should be able to work here... but using them might require some build system hackery in order to still support Java 1.6.

**Comment by henri-tremblay** [comment]
Wait until we drop 6?

**Comment by benmccann** [comment]
I would strongly like to drop support for Java 6. Java 7 was EOL in April 2015 and Java 8 has already been adopted by the vast majority of the community, so I think dropping Java 7 would be reasonable as well. Almost all the other projects I use like Play Framework, Spark, etc. have dropped Java 7 support long ago.

Dropping support for Java 7 would allow us to use Java 8 time API (https://github.com/ehcache/ehcache3/issues/2068) instead of making our own time API and improve our static analysis (https://github.com/ehcache/ehcache3/issues/903)

Is there anything that would be stopping us from dropping support for these older versions or any plan on when we could do so?

**Comment by benmccann** [comment]
I just saw the README says:

> We are also considering moving to Java 8 support only for the upcoming 3.5.0.

Is there anywhere that discussion is being had or anyone else who should be looped in? Is that a change we can go ahead and make?

**Comment by ljacomet** [comment]
@benmccann The decision itself is not something up for discussion as it impacts not just the open source version.

However, once a decision is made for `3.5.0`, we will definitely have a discussion on the [dev mailing list](https://groups.google.com/forum/#!forum/ehcache-dev).

I am however interested in understanding better why you seem so passionate about it. What are the issues Java 6 support are causing you? And actually the dev mailing list might be the better place to have this discussion rather than in issue comments.

**Comment by chrisdennis** [comment]
Once #2557 is merged it will become possible to run the OSGi tests in Java 9, and the regular tests in Java 11.

**Comment by chrisdennis** [comment]
Tests should now pass in Java 9 through 13 (my build of 13 at least). With two of caveats/carve-outs:

* OSGi tests are disabled in Java 11+ since I couldn't find a JAXB provider that is a valid OSGi bundle and bnd refuses to autogenerate the manifest because it barfs on the module-info.class
* Clustered tests are disabled in Java 11+ since the TC Server doesn't declare a jaxb runtime dependency properly.
