### ISSUE TITLE
How to read from disk data file?

### ISSUE THREAD

**Issue by zhxh24** [ehcache/ehcache3#2096]
I wrote data to my hard disk via ehcache, but I didn't know how to read it.
Here is my configuration file.
<cache name="log" 
      maxElementsInMemory="1"
      diskPersistent="true"
      eternal="true"
      overflowToDisk="true">
    <bootstrapCacheLoaderFactory
        class="net.sf.ehcache.store.DiskStoreBootstrapCacheLoaderFactory" 
        properties="bootstrapAsynchronously=true"/>
</cache>

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

There is nothing special to do to be able to read when restarting the application. However you must make sure that the `CacheManager` is closed properly on application shutdown otherwise the data written to disk will be discarded on restart.
