### ISSUE TITLE
Ehcache iterator throws RuntimeException in response to CacheAccessException in Store on Iterator.next() 

### ISSUE THREAD

**Issue by timeck** [ehcache/ehcache3#214]
See `org.ehcache.Ehcache.CacheEntryIterator.next()`

This iterator was reworked to make it interact with the Store in the way the 107 TCK expects. In particular it expected that the access time of each entry returned in the iterator is not touched until `next()` is called. In the previous implementation of `org.ehcache.Ehcache.CacheEntryIterator` the call to the store iterator's `next()` happened eagerly when the `org.ehcache.Ehcache.CacheEntryIterator` created

I don't think the 107 expectation is horrible and completely wrong, but it could maybe be relaxed to just expect the total number of access checks after iterating the cache.

**Comment by albinsuresh** [comment]
Identified an issue with the `CacheAccessException` handling contract between the store and the cache. In case of a store failure, store is supposed wrap/handle the exceptions thrown from that level and only throw a `CacheAccessException` to the cache level. But this contract is not honoured in most of the store APIs. `AbsractOffheapStore.get()` being an example. Because of this all the runtime exceptions happening at the store level bleed through to the cache level bypassing the resilience strategy as expected.

**Comment by ljacomet** [comment]
@albinsuresh Please isolate in its own commit the work to transform `RuntimeException` from the underlying data structures into `CacheAccessException` at the store level.
Then do the discussed work on making the iterator remember exception raised during `advance` and throw them when used.

**Comment by albinsuresh** [comment]
A single resilience strategy is insufficient for both iterator creation and performing an iteration.

With a resilience strategy in place, the iterator creation need not fail even in the case of an underlying store failure. As our default implementation a non-iterable iterator can be created and returned in that case(by remembering the failure and returning false on _hasNext()_ and throwing on _next()_).
But in the case of a failure happening in the middle of an iteration, the safest default resilience strategy we could take is to throw a runtime exception.

So the default resilience strategy for iterator creation is not to throw and return an non-iterable iterator. The strategy for an actual iteration is to throw. This is the reason why I'm thinking of splitting the resilience strategy for iteration operations.

After the discussion that I had with @lorban, we have decided to remove the _void iteratorFailure(CacheAccessException e)_ method from the `ResilienceStrategy` interface and replace that with 2 more specific ones:

```java
  /**
   * Called when a cache iterator creation fails due to an underlying store
   * failure.
   *
   * @param e the triggered failure
   * @return the entry to return from the operation
   */
  Iterator<Cache.Entry<K, V>> iteratorFailure(CacheAccessException e);

  /**
   * Called when a cache iterator advancement fails due to an underlying store
   * failure.
   * 
   * @param e the triggered failure
   * @return the entry to return from the operation
   */
  Cache.Entry<K, V> iterationFailure(Iterator<Cache.Entry<K, V>> iterator, CacheAccessException e);
```

We believe that these 2 methods give the maximum flexibility to the user to take whatever crazy resilience strategy they want to take.

The _iterationFailure()_ method takes in the iterator because we felt that the user may want to retry the iteration using the failing iterator or do something else with that iterator. By making the method return a `Cache.Entry<K, V>`, the user can use it to return some kinda sentinel/mock object that he can handle. So more flexibility to the user.

That being said, if we have overlooked something please let us know.
