### ISSUE TITLE
Outcomes for put() of an immediated expired value, and for a remove() that removes nothing

### ISSUE THREAD

**Issue by timeck** [ehcache/ehcache3#220]
At the moment there is no `end()` call on the observer in these scenarios. Do we want a discreet outcome for these paths? The code contains XXX comments asking this same question.

**Comment by lorban** [comment]
My personal logic tells me that there shouldn't be special cases for these two use-cases but the 107 TCK dictates otherwise: there are two tests checking for those specific cases:

 - put that immediately expires does not get reported as a put in the stats
 - remove on a non-existent key does not get reported as a remove in the stats

The goal of this issue is now to figure out a way to make our code behave as the 107 TCK mandates while not encumbering it with 107-specific logic.
