### ISSUE TITLE
what's the algorithm of evicting items in off-the-heap store

### ISSUE THREAD

**Issue by shengc** [ehcache/ehcache3#2271]
There is an eviction prioritizer in on-heap store that dictates the least recent accessed item should be evicted first. However there is no such thing in off-the-heap store implementation. From what I can find out, the eviction seems to be pretty random and sometimes evicts the item that is most recently updated. I am wondering is there no way to configure that. I know there is an eviction advisor, but its interface only gives the key and value for advise eviction with, which does not tell how the access time should be considered when an eviction must happen.

**Comment by chrisdennis** [comment]
The offheap implementation use a clock eviction algorithm - there is no way to configure or change this (sort of code modifications).

**Comment by shengc** [comment]
if off-the-store can spuriously evict items without any determined order, then this is mostly useless in many scenarios. Any reason why this has to be clock eviction, and no reconfiguration is allowed ? I find the level of customization allowed by ehcache 3 is a bit hostile to the users, while the previous version indeed provides more flexibility regarding this: http://www.ehcache.org/documentation/2.7/apis/cache-eviction-algorithms.html

**Comment by chrisdennis** [comment]
I'm afraid I disagree with your statement *"if off-the-store can spuriously evict items without any determined order, then this is mostly useless in many scenarios."*.  Offheap eviction has always been clock based in every version of Ehcache.  It's clock based in order to provide a reasonable balance of performance.  In general a perfectly deterministic eviction strategy for a cache is a luxury that most cannot afford, and even fewer (if any) actually need.
