### ISSUE TITLE
@Cacheable not working with programmaticial created caches

### ISSUE THREAD

**Issue by heikorm** [ehcache/ehcache3#2409]
Ehcache isn't working properly in my project. I run grails 3.3.1 "with org.grails.plugins:cache-ehcache:3.0.0.M1" and since i dont know where to put the ehcache.xml file and how the file should look like i tried to configure ehcache programmaticially

I created a cacheService with a methode "initCaches" which i run from my bootstrap.groovy

`class CacheService {
void initCaches() {       
    CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
        .withCache("sevenSeconds", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class, ResourcePoolsBuilder.heap(10))
            .withExpiry(Expirations.timeToLiveExpiration(Duration.of(7, TimeUnit.SECONDS)))
        )
        .withCache("twentySeconds", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class, ResourcePoolsBuilder.heap(10))
            .withExpiry(Expirations.timeToLiveExpiration(Duration.of(20, TimeUnit.SECONDS)))
        )
        .build()  
    cacheManager.init()
}
}`

When I start the application the console says that the caches have been created:

`2018-06-26 15:47:31.302  INFO --- [           main] org.ehcache.core.EhcacheManager          : Cache 'sevenSeconds' created in EhcacheManager.
2018-06-26 15:47:31.310  INFO --- [           main] org.ehcache.core.EhcacheManager          : Cache 'sevenSeconds' created in EhcacheManager.
`

Now I access a service method which is annotated with @Cacheable("sevenSeconds") and there comes the part which is confusing me: Again the console says, that the cache has been created (instead of putting the result into the old already out of CacheService created one):

`2018-06-26 15:47:31.302  INFO --- [           main] org.ehcache.core.EhcacheManager          : Cache 'sevenSeconds' created in EhcacheManager.
`

If i access the service again with same parameters a cached result will returned BUT the timeToLive is NOT 7 seconds like I created the cache in my CacheService.

It looks like @Cacheable doesn't consider my created caches in CacheService

Does anybody know what I am doing wrong?

thx

See Stack Overflow question here: https://stackoverflow.com/questions/51045205/eh-cache-with-grails-3

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***
Regarding XML configuration, have a look at http://www.ehcache.org/documentation/3.5/xml.html
Also this question is most likely an integration one, but there are no details on your Grails setup.

I would recommend you start with a clean setup or even a caching sample in order to understand where your current solution might be lacking some wiring.

And follow up conversations should happen on the mailing list or Stackoverflow, so closing this.
