### ISSUE TITLE
terracotta-statistics dependency should be relocated to another package during shading

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#2475]

**Comment by chrisdennis** [comment]
+0.5?

`terracotta-statistics` is also depended on by other projects... we might have to be careful here around when/how the shading happens to avoid complication on that front.

**Comment by ljacomet** [comment]
Hi Ehcache team,

I would recommend to tread carefully here. The shading Ehcache does is problematic in many ways, including for Java 9 module compatibility.
When we discussed this topic last, which means a couple months ago, we were even suggesting to deprecate the shaded `ehache-<version>.jar` and instead target user at the smaller ones.
And in that world, the statistics library will just be another jar out there.

**Comment by henri-tremblay** [comment]
@ljacomet Hello Louis. Not really. I'm all for stopping to produce an uber jar for ehcache. However, I still think statistics should be shaded and relocated to prevent clashing with other users of the library. I don't think the two strategies are antagonistic. It gives the flexibility of changing the API. Otherwise, we need to be super strict on API changes in statistics.

**Comment by chrisdennis** [comment]
Statistics is being relocated now. The world did not implode as predicted by ~Chicken Little~ @ljacomet .
