### ISSUE TITLE
I am also facing similar issue with Ehcache 3.x version and getting below exception with JDk11. So any idea to fix this.

### ISSUE THREAD

**Issue by ripunjDev** [ehcache/ehcache3#2713]
I am also facing similar issue with Ehcache 3.x version and getting below exception with JDk11. So any idea to fix this.

EXCEPTION STACK TRACE = Unable to make field private jdk.internal.reflect.ConstructorAccessorImpl jdk.internal.reflect.DelegatingConstructorAccessorImpl.delegate accessible: module java.base does not "opens jdk.internal.reflect" to unnamed module @1e6a3214

ERROR STACK TRACE = [java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340), java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280),

_Originally posted by @ripunjDev in https://github.com/ehcache/ehcache3/issues/2671#issuecomment-543531248_

**Comment by chrisdennis** [comment]
If you want to use byte-based sizing in Ehcache 3 in a modular JVM you will need to break open any module that contains cached classes to allow the Ehcache 3 code to access them. This is because Ehcache does byte-based sizing by walking the object graph using reflection and sizing the actual objects stored in heap. That should mean a sequence of:
```
--add-opens ${module}/${package}=ALL-UNNAMED
```
The exact sequence obviously depends on what types you are storing in the cache.

FYI: The reason this works in Hazelcast is because Hazelcast isn't really sizing objects on heap. Instead it's serializing the object and then sizing that byte array.
