### ISSUE TITLE
what is defalut expiry policy for ehcache3

### ISSUE THREAD

**Issue by hx78** [ehcache/ehcache3#2841]
if  do not set any expiry polcy in xml file or code , which expiry policy will be used?

for example, no set expiry policy

`<cache alias="withExpiry">`
`<heap>100</heap>`
`</cache>`

@jdillon

**Comment by chrisdennis** [comment]
If there is no expiry policy set then there is no expiry. Values added to the cache will never be removed because they have been in the cache for "too long". They will only be removed due to capacity eviction.

P.S. In the future please direct user support questions to the ehcache-user mailing list: https://groups.google.com/g/ehcache-users

**Comment by hx78** [comment]
tks @chrisdennis
