### ISSUE TITLE
How to limit mem use?

### ISSUE THREAD

**Issue by ZhiqinYang** [ehcache/ehcache3#2921]
I have code like this :
```
public class App {




    public static Cache<String, Long> buildPersistenceStorageCache(String cacheName, String path ) throws IllegalStateException {

        LocalPersistenceService persistenceService = new DefaultLocalPersistenceService(new DefaultPersistenceConfiguration(new File(path, cacheName)));

       return  UserManagedCacheBuilder.newUserManagedCacheBuilder(String.class, Long.class)
                .with(new UserManagedPersistenceContext<String, Long>(cacheName, persistenceService))
                .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder().heap(10)
                        .disk(10L, MemoryUnit.TB, true))
                .build(true);
    }


    public static void main(String[] args) throws Exception {
         Cache<String, Long> cache = buildPersistenceStorageCache("test", "/tmp");
         cache.clear();
         long now=  System.currentTimeMillis();
         long max = 900000000L;
         for (int i = 0; i <  max;i++) {

             if(i % 10000000 ==0 ) {
                 System.gc();
             }
             cache.put(i+"", (long)i);
         }
    }
}
```

It cost much memory ! how can i limit it ?  I
`
 jmap -histo:live 11677

 num     #instances         #bytes  class name
----------------------------------------------
   1:     107654138     5167570960  [B
   2:     107653695     5167377360  java.nio.HeapByteBuffer
   3:      53826845     2583688560  java.util.concurrent.ConcurrentHashMap$TreeNode
   4:      53826845     2153073800  org.ehcache.shadow.org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine$FileWriteTask
   5:      53827886     1291869264  java.lang.Long
   6:      53826850     1291844400  java.util.concurrent.LinkedBlockingQueue$Node
   7:            69      536896752  [Ljava.util.concurrent.ConcurrentHashMap$Node;
   8:       2097152      100663296  java.util.concurrent.ConcurrentHashMap$TreeBin
   9:          9276         698056  [C
  10:          2542         284008  java.lang.Class
  11:          9262         222288  java.lang.String
  12:          2187         117776  [Ljava.lang.Object;
  13:          3152         100864  java.util.concurrent.ConcurrentHashMap$Node
  14:          1181          71152  [I
  15:           744          65472  java.lang.reflect.Method
  16:          1886          60352  java.util.HashMap$Node
  17:          2437          38992  java.lang.Object
  18:           327          37744  [Ljava.util.HashMap$Node;
  19:           473          34056  java.lang.reflect.Field
  20:          1208          29848  [Ljava.lang.Class;
  21:           693          27720  java.util.LinkedHashMap$Entry
`

**Comment by chrisdennis** [comment]
As it stands the Ehcache open source disk store uses an unbounded write queue to buffer up pending disk writes. That queue is flushed on cache shutdown to ensure that everything is persisted. There isn’t currently a way to manually flush it (that I can recall). The OOME you are seeing is caused by the backing up of that queue. The only way to alleviate it would be to either replace the queue with a bounded one (and deal with the subsequent back-pressure), throttle the writing threads manually, or not to bulk load the cache in this way. Which of those is correct, and whether there is justification here for a feature request is hard to say without knowing how this artificial performance/load test relates to your presumed real usecase.

Chris

From: ZhiqinYang ***@***.***>
Date: Monday, July 12, 2021 at 6:08 AM
To: ehcache/ehcache3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ehcache/ehcache3] How to limit mem use? (#2921)

I have code like this :

public class App {









    public static Cache<String, Long> buildPersistenceStorageCache(String cacheName, String path ) throws IllegalStateException {



        LocalPersistenceService persistenceService = new DefaultLocalPersistenceService(new DefaultPersistenceConfiguration(new File(path, cacheName)));



       return  UserManagedCacheBuilder.newUserManagedCacheBuilder(String.class, Long.class)

                .with(new UserManagedPersistenceContext<String, Long>(cacheName, persistenceService))

                .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder().heap(10)

                        .disk(10L, MemoryUnit.TB, true))

                .build(true);

    }





    public static void main(String[] args) throws Exception {

         Cache<String, Long> cache = buildPersistenceStorageCache("test", "/tmp");

         cache.clear();

         long now=  System.currentTimeMillis();

         long max = 900000000L;

         for (int i = 0; i <  max;i++) {



             if(i % 10000000 ==0 ) {

                 System.gc();

             }

             cache.put(i+"", (long)i);

         }

    }

}

It cost much memory ! how can i limit it ? I
`
jmap -histo:live 11677

num #instances #bytes class name

1: 107654138 5167570960 [B
2: 107653695 5167377360 java.nio.HeapByteBuffer
3: 53826845 2583688560 java.util.concurrent.ConcurrentHashMap$TreeNode
4: 53826845 2153073800 org.ehcache.shadow.org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine$FileWriteTask
5: 53827886 1291869264 java.lang.Long
6: 53826850 1291844400 java.util.concurrent.LinkedBlockingQueue$Node
7: 69 536896752 [Ljava.util.concurrent.ConcurrentHashMap$Node;
8: 2097152 100663296 java.util.concurrent.ConcurrentHashMap$TreeBin
9: 9276 698056 [C
10: 2542 284008 java.lang.Class
11: 9262 222288 java.lang.String
12: 2187 117776 [Ljava.lang.Object;
13: 3152 100864 java.util.concurrent.ConcurrentHashMap$Node
14: 1181 71152 [I
15: 744 65472 java.lang.reflect.Method
16: 1886 60352 java.util.HashMap$Node
17: 2437 38992 java.lang.Object
18: 327 37744 [Ljava.util.HashMap$Node;
19: 473 34056 java.lang.reflect.Field
20: 1208 29848 [Ljava.lang.Class;
21: 693 27720 java.util.LinkedHashMap$Entry
`
