### ISSUE TITLE
Ehcache 0B of physical memory when using containerd

### ISSUE THREAD

**Issue by letthefireflieslive** [ehcache/ehcache3#2934]
Experiencing 

> java.lang.IllegalArgumentException: Attempting to allocate 50.0MB of memory when the host only contains 0B of physical memory

when we try to start our application baked in a docker image and the container runtime used is **containerd** 1.3.7. 

The application started successfully when the container runtime used is docker either in local or as container runtime for kubernetes.

ecache version: 3.9.3
containerd version: 1.3.7
os: rhel 7
packaged via gradle and jib

**Comment by chrisdennis** [comment]
I've seen this same issue once before but couldn't get cooperation from the owner of the environment to investigate it. I believe it's related to the introduction of https://www.oracle.com/java/technologies/javase/8u261-relnotes.html#JDK-8226575. It's likely that this is a bug in one or more layers of that stack (or potentially an interaction between the right combinations). If I'm right then I suspect that adding `-XX:-UseContainerSupport` to the Java options should avoid the issue (albeit at the cost of the JVM ergonomics being less aware of the containers sizing/attributes). It's also possible that this bug has been fixed in later version of the JDK and that judicious upgrades could help. If a work-around can't be found it will require a new release to allow the check to be bypassed.

FYI: a quick way of testing the effect of the environment/option changes is to execute the PhysicalMemory class directly:
```
java -cp ehcache-3.9.3.jar:slf4j-api-1.7.25.jar:slf4j-simple-1.7.25.jar org.ehcache.shadow.org.terracotta.offheapstore.util.PhysicalMemory
Total Physical Memory: 32GB
Free Physical Memory: 1.3GB
Total Swap Space: 2GB
Free Swap Space: 951.2MB
Committed Virtual Memory: 14.2GB
```

**Comment by letthefireflieslive** [comment]
thanks @chrisdennis works for us using jdk 11.0.2-open with the flag -XX:-UseContainerSupport
