### ISSUE TITLE
DefaultStatisticsService removed between 3.9.0 and 3.9.6

### ISSUE THREAD

**Issue by chuckdumont** [ehcache/ehcache3#2951]
I'm trying to upgrade from 3.9.0 to 3.9.6 and I've found that org.ehcache.core.statistics.DefaultStatisticsService has been removed.  Leaving aside the the fact that this type of change should not have been made in a patch release, how do I need to change my code to accommodate this?

```java
    StatisticsService statsService = new DefaultStatisticsService();
    cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
        .withCache(ALIAS, CacheConfigurationBuilder
            .newCacheConfigurationBuilder(String.class, CacheEntry.class, 
                ResourcePoolsBuilder.heap(maxCacheEntries)
            )
            .withLoaderWriter(new PhotoCacheLoader(new StatIncrementer(loads)))
            .build()
        )
        .using(statsService)
        .build(true);
```

**Comment by chuckdumont** [comment]
I fixed my compilation error by changing the import from org.ehcache.core.statistics.DefaultStatisticsService to org.ehcache.core.internal.statistics.DefaultStatisticsService.  But assuming internal classes shouldn't be used, what is the supported way to do this?

**Comment by chrisdennis** [comment]
*Started writing the following before you're second comment:*

`DefaultStatisticsService` has moved from `org.ehcache.core.statistics` to `org.ehcache.core.internal.statistics` because it's an internal implementation class. This is why that package is not (and was not) included in the published API javadoc.

That said if you want to retrieve statistics for a cache the best way to do that right now is probably the following:

```java
StatisticsRetrieval statsRetrievalService = new StatisticsRetrieval();

try (CacheManager cacheManager = newCacheManagerBuilder()
  .withCache("foo", newCacheConfigurationBuilder(String.class, String.class, heap(1000)))
  .using(statsRetrievalService)
  .build(true)) {

  StatisticsService statisticsService = statsRetrievalService.getStatisticsService();

  Cache<String, String> cache = cacheManager.getCache("foo", String.class, String.class);
  cache.put("foo", "bar");
  cache.get("foo");

  CacheStatistics foobar = statisticsService.getCacheStatistics("foo");
  System.out.println(foobar.getCachePuts());
  System.out.println(foobar.getCacheGets());
}
```
where `StatisticsRetrieval` looks like this:
```java
@ServiceDependencies(StatisticsService.class)
public class StatisticsRetrieval implements Service {

  private StatisticsService statisticsService;

  @Override
  public void start(ServiceProvider<Service> serviceProvider) {
    this.statisticsService = serviceProvider.getService(StatisticsService.class);
  }

  @Override
  public void stop() {
    this.statisticsService = null;
  }

  public StatisticsService getStatisticsService() {
    return requireNonNull(statisticsService);
  }
}
```
This will get you a reference to the manager's statistics service of choice without imposing a specific implementation. This is also more likely to survive without needing modification on upgrades. Note however that `StatisticsService` is an SPI class and so is also not guaranteed to be stable under the semantic versioning scheme used by Ehcache.

**Comment by chuckdumont** [comment]
Thanks for the explanation, and I take your point about the class not being officially documented, however, I still think that this change should have waited till 3.10.  Patch releases are supposed to be drop-in replacements for the same minor release that don't require any code changes.  Changing the package hierarchy of an internal class that wasn't clearly labeled as internal, and which is talked about in numerous posts online, doesn't fit with that pattern.
