### ISSUE TITLE
Add flag for enabling/disabling with <cache/>

### ISSUE THREAD

**Issue by onacit** [ehcache/ehcache3#2970]
This may seem to somewhat related to Spring Framework.

I'm using Ehcache with my Spring Boot application with following strategy.

* I need(decided) to cache Repository interface methods not Service methods.
* Instead of annotating my repository methods with `@Cacheable`,
* I created an Aspect invokes around every methods of all repository interfaces and checks cache for FQMN.

That means...
```java
interface MyRepository {

    // Not annotated with @Cacheable
    void doSome();

    // Not annotated with @Cacheable
    Some doWhatever();
}

class RepositoryAspect {

    @Around
    Object around_any_method(...) {
        // Find the FQNM and check the cacheManager
        // If found and exists, return the cached values.
        // else proceed
   }
}
```

And here comes my `ehcache.xml`

```xml
  <cache alias="....MyRepository#doSome">
  </cache>
```

And the way of turning-off the caching for the specific method is deleting or commenting the block.

I think it'll be great if I have `@enabled` attribute or some.

```xml
  <cache alias="....MyRepository#doSome" enabled="false" >
  </cache>
```

**Comment by chrisdennis** [comment]
Cache enable/disbale isn't a concept in Ehcache 3. It used to exist in Ehcache 2 but we decided to not keep it when advancing to 3. The idea of "disabling" a cache was left as something for the user to control since the semantics are ill defined, particularly in a system where the "cache" extends beyond the bounds of the immediately accessible JVM. Disabling a "clustered cache" (via JMS/TC or whatever) for example might mean not reading but still writing to avoid data consistency issues in other clients.
