### ISSUE TITLE
JAXB breaks Intellij Maven resolving

### ISSUE THREAD

**Issue by thhart** [ehcache/ehcache3#3123]
I know it is on Intellij side, however I want to inform you I filed a bug there. I wanted to include your Maven dependency and suddenly Intellij got broken. I t can not resolve any dependencies any more.

https://youtrack.jetbrains.com/issue/IDEA-312419/JAXB-dependency-breaks-all-Maven-resolving?clearDraft=true&description=%0A%0AIU-223.8617.56,%20JRE%2017.0.5%2B1-b653.25x64%20JetBrains%20s.r.o.,%20OS%20Linux(amd64)%20v5.15.0-58-lowlatency,%20screens%205760.0x3240.0

**Comment by chrisdennis** [comment]
Added a comment to the IntelliJ issue. I'm pretty sure this is due to your repository set exposing a latest jaxb-runtime version that has an unresolvable transitive dependency set. You'll either need to pick a specific version of jaxb-runtime that resolves correctly, modify your repository set to find the needed reps, or take it up with the repository owner(s).

**Comment by maroony** [comment]
@chrisdennis Maybe because of this and #2925 it would be better to not using version ranges in dependencies. It also causes problems in Eclipse IDE.

So replacing 

```xml
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>[2.2,3)</version>
      <scope>runtime</scope>
    </dependency>
```

with 

```xml
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>2.3.9</version>
      <scope>runtime</scope>
    </dependency>
```

would solve those problems. What do you mean?
