### ISSUE TITLE
what is the maximun allow key size and vaule size?

### ISSUE THREAD

**Issue by river320** [ehcache/ehcache3#3143]
https://github.com/ben-manes/caffeine/issues/881
Thank you

**Comment by chrisdennis** [comment]
This is not throughly tested, but in principle object sizes and cache capacities are maintained as longs.  The offheap areas are also long addressed. So I guess technically Long.MAX_VALUE for both key size and value size? The practical limit is going to be lower due to JVM memory constrains and a user's responsiveness requirements. In that sense the technical limit is not a very interesting one.
