### ISSUE TITLE
Add Type Parameter in read method of Serializer Interface

### ISSUE THREAD

**Issue by JSAhuja** [ehcache/ehcache3#420]
It will nice to have a paramater 'type' in read method of the Serializer.
something like:
 public T read(ByteBuffer binary,  Class<T> type)

**Comment by aurbroszniowski** [comment]
to give more context:
providing the type of the class to org.ehcache.spi.serialization.Serializer implementations can help for custom serialization, e.g. when using kryo, this would allow to use  :
```
kryo.readObject(unsafeInput, classType);
```
for deserialization, and not delegate to kryo the resolution of the serialized class type (thus using a smaller footprint)

**Comment by chrisdennis** [comment]
The cache doesn't know what the concrete types of the keys and values are, therefore it can't know what type to pass to this method.  It only knows what the key and value type of the cache are.  For example if my cache is Cache<Integer, CharSequence> I don't know if a given value is a String, a CharBuffer or something else entirely.

If a users want to achieve this they can do so with a serializer type that takes a class on construction. Then on calls to serialize it will check that the passed object is a instance of precisely that class. On deserialization it can then pass that class in itself, rather than relying on the cache to do it.
