### ISSUE TITLE
Investigate churn created by Ehcache 3

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#507]
The reason for this issue comes from the following micro benchmarks results:

Setup
* Keys: long; values: byte[1000] with randomized content - 2,000,000 entries
* Ehcache 2.9.1, pure on-heap, max elements = Integer.MAX_VALUE (eh2 in results)
* Ehcache 3.0.0-SNAPSHOT, pure on-heap user managed cache, max elements = Long.MAX_VALUE (eh3 in results)

I then ran two tests with 4GB and 8GB heaps.

Results follow:
````
==> results-eh2-4g.txt <==
"Benchmark","Mode","Threads","Samples","Score","Score Error (99.9%)","Unit"
"org.ehcache.CacheBenchmark.testGetEhcache2","thrpt",20,20,24274469.272589,1612218.164819,"ops/s"

==> results-eh2-8g.txt <==
"Benchmark","Mode","Threads","Samples","Score","Score Error (99.9%)","Unit"
"org.ehcache.CacheBenchmark.testGetEhcache2","thrpt",20,20,30344616.164551,270831.911948,"ops/s"

==> results-eh3-4g.txt <==
"Benchmark","Mode","Threads","Samples","Score","Score Error (99.9%)","Unit"
"org.ehcache.CacheBenchmark.testGetEhcache3","thrpt",20,20,7362629.399195,776230.819703,"ops/s"

==> results-eh3-8g.txt <==
"Benchmark","Mode","Threads","Samples","Score","Score Error (99.9%)","Unit"
"org.ehcache.CacheBenchmark.testGetEhcache3","thrpt",20,20,43161946.345913,3398501.848252,"ops/s" 
````

What is clear is that Ehcache 3 creates more churn than Ehcache 2 but is otherwise faster when not under memory pressure.

After discussion with the team, we believe this is an item that will need attention once we have all the major features in, in order to find the best way to resolve it.

**Comment by lorban** [comment]
Investigation has shown that Ehcache 2 generates almost zero churn when under read-only load: not a single new object is created under the Cache.get() path, while Ehcache 3 can easily generate a gigabyte per second on a 8 cores machine just because of the few new objects we allocate under the Cache.get() path.

A quick and dirty prototype that makes o.e.c.Ehcache.get() call Store.get() instead of Store.computeIfAbsent() and OnHeapStore.get() call CHM.get() instead of CHM.computeIfPresent() would reduce the amount of churn generated by Ehcache 3 by about 65% and make it beat Ehcache 2 even under heap pressure.

The last bit of churn that Ehcache 3 would need to get rid of to be 100% "no new in get() path" would be to find a way to eliminate the new LookupOnlyOnHeapKey() in OnHeapStore.MapWrapper.get().

**Comment by lorban** [comment]
#777, #787 and #791 took care of that.
