### ISSUE TITLE
Potential resource leak when closing a Cache

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#562]
When closing a `Cache`, if anyone holds a reference to it, most of the consumed resources will remain referenced.

We need to eagerly clear resources like the underlying `Store`.

Pay attention to the references potentially held by the listeners registered for lifecycle events.

**Comment by ljacomet** [comment]
Had a look at what happens in detail and I do not think we have an issue.

* When closing the cache, everything it uses and has an explicit lifecycle will have their `close()` method invoked.
  * For disk and off heap tiers, this includes clearing the reference to the offheap map thus allowing the offheap allocated memory to be reclaimed by the JVM.
  * For onheap, it means clearing the map but not nulling it.
* However, the cache still holds references to the tiers and utilities like `Serializer`, `CacheLoaderWriter`
  * These are needed because in the case of a `UserManagedCache` calling `init()` then `close()` in a loop is valid (do not do it though!)

So Ehcache 3 makes sure the most memory hungry bits (tiers) are properly cleaned up and it offers everything needed thorough the lifecycle so that users implementing their own `CacheLoaderWriter` are not relying on _GC_ to have their connections, state and more cleaned up.

In this context, I am closing this as _not a bug_.

**Comment by seabamirum** [comment]
I'm using Spring 4.3.3 and EHCache 3.1.3 as a JCacheCacheManager. When I stop my web application, Tomcat complains bitterly:

The web application appears to have started a thread named [MappedByteBufferSource Async Flush Thread] but has failed to stop it. This is very likely to create a memory leak.

This is followed by dozens of:

The web application  created a ThreadLocal with key of type [org.ehcache.impl.internal.concurrent.Threa\
dLocalRandom$3] (value [org.ehcache.impl.internal.concurrent.ThreadLocalRandom$3@71278bdb]) and a value of type [java.lang.Integer] (value [0]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

I don't understand why this is happening, since spring definitely calls close() on the cacheManager when the context is destroyed. Sorry if this isn't the right place to post this but it was the most closely related issue I could find.

```java
@Override
	public void destroy() {
		this.cacheManager.close();
	}
```

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

In this case, please let's do that as we would need information around configuration in order to try to reproduce. And that's certainly not going to happen on a closed issue.

Regards,
Louis
