### ISSUE TITLE
Allow configuring instances for services extending ClassInstanceProvider

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#635]
Currently, services extending ClassInstanceProvider like DefaultCacheEventListenerProvider and DefaultCacheLoaderWriterProvider only accept a class name in their configuration.

Shouldn't we allow configuring either a class name or an instance? That would make the configuration a bit more flexible.

BTW, DefaultCopyProvider already accepts an instance as that was required by the XAStore.

**Comment by ljacomet** [comment]
I am in favour of generalising this.

Others?

**Comment by albinsuresh** [comment]
Inorder to generalise this `ClassInstanceConfiguration` will be modified to hold the instance provided by the user. `ClassInstanceProvider.newInstance` also will have to be modified to return the user provided instance if one exists, else do the instantation as it is currently. With these changes the only requirement at the service configuration levels is to have an extra constructor that takes in an actual service instance.

This would work for copiers, loader-writers and event listeners but not for serialisers because the serialisation provider does not extend `ClassInstanceProvider` provider anymore. @chrisdennis did the refactoring of `DefaultSerializationProvider` recently and he must have had a good enough reason to do that. The goal can be achieved even with this exceptional case of serialisation provider by handling it separately. But I'm just attempting a refactoring of `DefaultSerializationProvider ` as well to make it extend `ClassInstanceProvider` so that everything is consistent. If anyone has any knowledge on why that refactoring was not done earlier and why doing it now wouldn't work either , please share.

**Comment by albinsuresh** [comment]
With the changes done for this task, the user will be able to configure the services as follows:

```java
CacheConfigurationBuilder.newCacheConfigurationBuilder()
        .add(new DefaultCopierConfiguration<Description>(new DescriptionCopier(),
            CopierConfiguration.Type.KEY))
```

in addition to the current way of doing this:

```java
CacheConfigurationBuilder.newCacheConfigurationBuilder()
        .add(new DefaultCopierConfiguration<Description>(DescriptionCopier.class,
            CopierConfiguration.Type.KEY))
```

Even though the former is more intuitive for a regular java user, the amount of code that he has to write still remains somewhat same. Having to create a service configuration explicitly and sticking in an actual service instance in it is still bit of an overkill. How-about having specialised methods at the `CacheConfigurationBuilder` like _withKeyCopier_, _withValueSerializer_ etc so that it is much more intuitive to the user? Internally we can still get the job done with the service configurations. But the user facing API would look much cleaner this way. 

So configuring a copier like this as opposed to the code block given above:

```java
CacheConfigurationBuilder.newCacheConfigurationBuilder()
        .withKeyCopier(new DescriptionCopier())
        .withValueSerializer(new PersonSerializer())
```

Thoughts/Comments???

**Comment by albinsuresh** [comment]
After the discussion with @ljacomet @chrisdennis it has been identified that life-cycling of the things provided by different services(the copiers, serializers, loader-writers and cache event listeners) needs to be revisited inorder to solve this problem.
The major problem with the current design is that not all of these provided "things" are life-cyclable. So when we open the door for configuring user provided instances and when they are reused that'd cause problems. For example consider the serializers. `Serializer` is `Closeable` but not `LifeCycled`. So when the cache is closed the user provided serializer instance is also closed. But when the cache is reinitialized the serializer is not reinitialized. So the cache will be initialized with the serializer which has already been closed. Even this behaviour is not consistent across the provided things as some of them are `Closeable` and others are not. So once the user starts providing instances directly the life cycling of those needs to be defined/done properly too.
So shouldn't we standardize the life-cycle of these provided things by making them `LifeCycled`?

**Comment by albinsuresh** [comment]
As discussed, it has been decided that the contract of releaseXXX methods in the service providers would be to close the provided instances if and only if they are Closeable.

With that contract in place, injecting the instances through the service configurations as implemented in PR #655 should be reasonable I suppose. Please comment if there are any objections.

**Comment by ljacomet** [comment]
Sounds sane to me - so you will update PR #664 to use `Closeable` and then adapt PR #655 on top of it?

**Comment by albinsuresh** [comment]
Yes that's the plan. Did not get any feedback on my proposal to have specialized methods like _withCacheLoaderWriter_, _withKeySerializer_ etc on the `CacheConfigurationBuilder `. Does that mean that we are not considering it for the moment? Detailed proposal in my second comment under this issue.

**Comment by ljacomet** [comment]
Regarding the specialised methods addition, I believe this should be considered under #20 and not here.
Could you add these as a point to consider in #20?
