### ISSUE TITLE
DataLoader

### ISSUE THREAD

**Issue by publicocean0** [ehcache/ehcache3#671]
I m seeing you are rewriting ehcache from scratch in more similar way to hanzelcast cache. 
I send you a simple bug  in hanzelcast , it would be important do not do in a big data system as ehcache could be used. 
All the API for loading a set of data might be paginated, never never to introduce api like List<Serializable> findAll() ..... more better  List<Serializable> findAll(offset, limit ). 
If you wont to use pagination in API at least, use Iterator insteat List interface :) 
This simple modification can make many differences :)

ciao :)

**Comment by ljacomet** [comment]
There is no plan of having search related features in Ehcache 3, so no methods like `findAll(...)`.

Please use the [ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) google group to discuss such questions before opening an issue here.

**Comment by publicocean0** [comment]
it was not related only to seach features, but above all to layer for loading data from a database for example  on startup  for example :) In hanzelcast there is a Interface for loading elements from a generic datasource .... findAll is a method used by cache for loading all elements in cache (it is not equals to load all data in memory)

**Comment by alexsnaps** [comment]
Can you elaborate where that `findAll` method is (or would be) that you're talking about here? I miss to understand what you're referring to... `org.ehcache.spi.loaderwriter.CacheLoaderWriter#loadAll` maybe?

**Comment by publicocean0** [comment]
it was just a generic suggestion for every api handing a set of elements in cache.
org.ehcache.spi.loaderwriter.CacheLoaderWriter is is ok using Iterable interface :)
ciao have a good work

**Comment by alexsnaps** [comment]
Right, that's why `Cache<K, V> extends Iterable<Cache.Entry<K,V>>` now for the `CacheLoaderWriter` on the other hand, that's not the way to go. Mainly because it consumes "things" coming from the heap anyways (and no, this isn't a "streaming" API into the SoR through the `Cache`). Loader methods fall in somewhat the same boat, as the batch being passed isn't dictated by the user, but by the `AuthoritativeTier` the cache is configured to use (i.e. it batches say on keys matching a given segment of such a store). Anyways, looks like we're in agreement here then... and there is indeed nothing to do.
