### ISSUE TITLE
Configure without adding to CacheManager

### ISSUE THREAD

**Issue by sgjava** [ehcache/ehcache3#679]
This is an enhancement request if I'm understanding how configuration works. I'm testing with Ehcache and Apache JCS, Since Ehcache makes configuration visible to CacheManager without CacheManager.createCache if behaves differently from JCS provider. With JCS you must explicitly call createCache with the same cache name as in the ccf configuration file. Since Ehcache behaves differently calling createCache causes javax.cache.CacheException: A Cache named [cacheName] already exists. Is there a way to disable the automatic creation of caches in CacheManager? If not, can you add a configuration option to disable auto createCache?

**Comment by ljacomet** [comment]
Hi Steven,

What you are asking is already possible: just use cache templates instead of cache definitions in the config file. Make sure you do not forget to link the template to the cache name you want in the jar 107 service tag. See [this part](http://www.ehcache.org/documentation/3.0/107.html#supplement-jsr-107-s-configurations) of the documentation for details.

Also, in general, what you are asking would not be an option for Ehcache because it would mean the behaviour would be different when used inside JSR-107 and when used standalone.
In Ehcache, the definition of a cache in XML means the cache is made live the moment the `CacheManager` is initialized. Since JSR-107 does not offer any explicit lifecycle control, the underlying cache manager must be initialised when created by the JSR-107 call.

And finally, what would be the semantic of the passed in `javax.cache.configuration.Configuration` if we were to do what you ask?

So for all this reasons, I am closing this issue as _won't fix_.

**Comment by sgjava** [comment]
OK, thanks. I ended up using templates...
