### ISSUE TITLE
Remove eviction prioritize feature and compute eviction veto state on insert/update

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#690]
While it sounded like a good idea to have customisable eviction priorities, it turns out the be a performance problem that will be hard to address with the feature as it currently exists.

So in this context, we are dropping the feature to not block performance work later.

Regarding eviction veto, we are aligning the behaviour across tiers to a computation of the veto on insertion / update of the mapping.

**Comment by lorban** [comment]
There's a nice optimization/rationalization we could do regarding the veto state: if it was available from the ValueHolder interface, we could simply copy it across when mappings are being faulted to a caching tier instead of calling the veto predicate during each fault.

This would also simplify the veto calling code a bit as the only place it would be called is during initial insertion/update, ie: only ever triggered by a user call and never by the internal plumbing.

**Comment by ljacomet** [comment]
I can see usefulness in computing the veto again when a value moves between tiers. When it happens, internal stats of the Cache.Entry have changed and so the veto may end up with a different value.
