### ISSUE TITLE
Enable single resource declaration in XML

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#864]
Given the changes done around `Store.Provider` selection and the fact that you should now be able to create a cache with only offheap or disk as their unique tier, we should try to improve the basic Ehcache XSD to enable a single resource declaration of any type and not just heap.

**Comment by chrisdennis** [comment]
DId some investigation on this.  A simple solution is not possible due to limitations within the JAXB spec that prevent two elements within the same model class from being annotated with `@XmlAnyElement` - the existing one being the service configuration (https://java.net/jira/browse/JAXB-798).  The two potential solutions here are:

1. Adding additional 'core' resources to the choice to allow additional resources beyond heap.
2. Having two schemas for the config.  An internal one that is used to generate the JAXB model that is simpler, and a more complex one (likely an extension) that the user writes their config to.  Then we author an XSL transform that converts between the two.

For now @ljacomet and I propose leaving this as is and reopening when the users reopen this.
