### ISSUE TITLE
Large Full GC pauses (~2 sec)

### ISSUE THREAD

**Issue by skbansal** [ehcache/ehcache3#907]
Testcase 

JVM : 1.7.0.72
Ehcache : RC1
XMX, XMS : 4g
R:W : 90:10
Element : <Long(), byteArray()>
Tier : heap only

Noticed full gc pauses as large as 2 sec. This is causing spikes in latency.
[ehcache3_rc1_gc_logs.txt](https://github.com/ehcache/ehcache3/files/192249/ehcache3_rc1_gc_logs.txt)

**Comment by skbansal** [comment]
attaching ehcache2 gc logs which has got gc pauses of ~250ms only.
[ehcache2_gc_logs.txt](https://github.com/ehcache/ehcache3/files/192254/ehcache2_gc_logs.txt)

**Comment by chrisdennis** [comment]
Pretty sure this is due to https://bugs.openjdk.java.net/browse/JDK-8151101 which was fixed in Java 9 mainline as of March 30th 2016 (http://hg.openjdk.java.net/jdk9/jdk9/hotspot/rev/3f5a29b58493).  It might be worthwhile someone validating this with original testcase, but I saw improved performance in my minimal (non Ehcache based) testcase on a recent JDK 9 EA release.
