### ISSUE TITLE
Montreal design 'Emergency Valve' is not currently wired in.

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#919]
Currently if there is a size inversion and everything in the offheap tier is 'pinned' because it's all cached in the heap tier, there is no functional emergency valve to trigger clearing of the heap tier.  We should think about fixing this.

**Comment by ljacomet** [comment]
From looking at Ehcache 2.x, what happens when the valve is invoked is that the `CachingTier` is cleared in a way that notifies the authority, as we need to clear the faulted state.

There is currently no method on `CachingTier` in Ehcache 3 that allows to do that.
So we would at least need to add a `CachingTier.invalidateAll()` and a similar method on the `LowerCachingTier`.
We need that because the current `CachingTier.clear()` has no link at all with invalidation.
An alternate solution would be to add a boolean flag to `clear` to indicate if notifications are expected.

**Comment by ljacomet** [comment]
Extending the scope of this issue to take into account the upcoming needs from clustering.

In the context of the `ClusteredStore` we will want server originated invalidations, with key granularity. In that context, we need to extend the _emergence valve_ concept to account for this need.

Proposition to use the following interface:
``` java
interface InvalidationValve<K> {
  void invalidate(K key);
  void invalidateAll();
}
```

which would be injected in the `AuthoritativeTier` by the `TieringStore`.

As discussed in the previous comment, this will in turn require extra methods on the `CachingTier` and `LowerCachingTier`. Between the addition of a boolean to `clear` and the introduction of `invalidateAll`, since both are SPI changes anyway, I am in favour of the method addition to better indicate purpose.

Comments welcome!

**Comment by lorban** [comment]
Two remarks about that `InvalidationValve` interface:

 1) Shouldn't `void invalidate(K key)` be `void invalidate(Set<K> keys)` instead as the authority might invalidate batches of keys?
 2) Regarding the #1015 work, we are considering the need to add something like a `void refresh(K key, ValueHolder vh)` method to that interface to refresh the metadata of a caching tier's mapping instead of evicting it. WDYT?

**Comment by ljacomet** [comment]
I was on the fence about the `invalidate(K key)` signature. Now taking a `Set<K>` may mean extra allocations on that path. Maybe the best way is to keep in mind that the `InvalidationValve` is our way into `AuthoritativeTier` talking to `CachingTier` and we will add extra methods based on clustered needs.
So in short, I would limit the api in the context of this fix to:
``` java
interface InvalidationValve<K> {
  void invalidateAll();
}
```

Honestly, need to think some more about #1015 before I can answer the refresh question - and I would rather not do it here. To keep topics separated.

**Comment by lorban** [comment]
About #1015: sure, you can completely ignore that in this context, assuming the introduction of another method in the `InvalidationValve` won't cause any trouble - which I doubt it will.

**Comment by ljacomet** [comment]
coming full circle:
* `InvalidateValve` to be handled on master for Ehcache clustered - see #1030
* this will be a bug fix only - dropping the spi label
