### ISSUE TITLE
Clustered Ehcache Operations Network Messaging Research Spike

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#940]
Research spike on the necessary message set for the clustered Ehcache operation message set. This should be a relatively simple exercise, but I want the focus here to be on deciding how the messaging is done (proxy or native).

**Comment by AbfrmBlr** [comment]
I think we should use native approach for this.
The `voltron-proxy`, as it stands today is not in a state where it can used since the server to client communication has changed since the proxy was designed.
It would be a considerable effort to incorporate that and then make Ehcache's Server Side entity a proxied one.

Instead we can define a set of operations for the client side proxy of ServerStore.

General Structure of Message over the would like this :

Client invoking Server Side api :

`[Cache Identifier] [Type of Operation] [Operation Arguments]`

`Cache Identifier` :- Unique identifier for the cache(gets associated with cache during cache creation)

`Type of Operation` :- The kind of operation (encoded in bits) which client wants to do on server store.
					There are four operations `get`, `getAndAppend`, `append` & `replaceAtHead` which can be denoted in 2 bits.

`Operation Arguments` :- arguments required for the respective operation. The Codec should be able to
					   decode operation arguments based on the operation provided.

Server Side Response in lieu of the Request sent :

Get and GetAndAppend require response to be sent back to the client. 
Though the `InvocationBuilder` at platform level allows client to decide to wait/or to not wait for server to 
ack the message at different stages(recived, complete), some operations require response as well to continue.
All those responses would be sent as `EhcacheEntityResponse` to the client.  

`[Cache Identifier] [Chain of Elements in binary]`

`Chain of Elements in binary` :- As of now both the operations need Chain as the response back

**Comment by AbfrmBlr** [comment]
ReplaceAtHead as the special case :-

Replace Request :-
The request message needs special attention as this has to send `Chain` of `Element`s back to the server. 
All other operations require just handling of long and byte buffers which is simple to encode/decode.
In this case since replace has to be followed up by a get or getAndAppend, the expectation for client is to send the 
original `Chain`. Since server already has that knowledge of payload associated with the chain, client can just send an equivalent to
original chain which just has sequence numbers rather than the whole chain.
Here there is a need of a builder kind of construct to be made available at client side so the client is able to send a equivalent chain. 

Replace Response :-
Based on the Passive replication approach taken `replaceAtHead` will also require `boolean` as the response which can be easily accommodated as well.

**Comment by AbfrmBlr** [comment]
This is the approach is to handle client initiated communications through `EntityClientEndpoint` for cache operations.
Server initiated communications to send invalidation to clients may have to use a api either `ClientCommunicator` or https://github.com/Terracotta-OSS/terracotta-platform/tree/master/client-communicator-support (still to be decided based on #1007).
