### ISSUE TITLE
ehcache v3 example for Expiry API of a Cache

### ISSUE THREAD

**Issue by marti1125** [ehcache/ehcache3#997]
I'm trying to get time when if expired a cache 

http://www.ehcache.org/apidocs/3.0.0/org/ehcache/expiry/Expiry.html

Could you give an example?

**Comment by ljacomet** [comment]
Hi,

Thanks for your interest in Ehcache 3.

For this kind of questions, we recommend using the [ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) google group.

As noted in #995 there is missing documentation. This will be added with the next bug fix release, 3.0.1.

However, the idea behind expiry is that your application needs to decided the duration of validity for mappings, using the `Expiry` API to do so through one of the proposed version from `Expirations` or through a provided implementation.
And when actions are taken on cache mappings, a new expiry duration will be computed. If through one of these action, Ehcache finds the mapping expired, it just removes it and indicates to the user that no mapping was found.
There is no public API to query a cache about the expired state of a mapping ... because expired mappings are discarded.
